apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: cluster-0
  git:
    syncRepo: git@github.com:hengv/gkeaws.git
    syncBranch: master
    secretType: ssh
    policyDir: "policy"
